name: Deploy via FTP

on:
  push:
    branches:
      - dev  # Trigger the workflow when changes are pushed to the 'dev' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify Node.js version 18

    - name: Install Dependencies
      run: |
        cd frontend  # Change to the frontend directory where package.json is located
        npm install  # Install the dependencies

    - name: Build Angular App
      run: |
        cd frontend  # Change to the frontend directory
        npm run build --prod  # Build the Angular app

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/dist  # Path to the 'dist' folder
        server-dir: /public_html/walletplus.in/secure/  # Path on the remote server
